apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-secret
  namespace: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: lldap-secret
    creationPolicy: Owner
  data:
    - secretKey: LLDAP_JWT_SECRET
      remoteRef:
        key: /ldap/
        property: LLDAP_JWT_SECRET
    - secretKey: LLDAP_LDAP_USER_PASS
      remoteRef:
        key: /ldap/
        property: LLDAP_LDAP_USER_PASS


