app-template:
  image:
    repository: ghcr.io/onedr0p/plex
    tag: 1.31.0.6654-02189b09f
  controller:
    replicas: 1
    type: statefulset
  env:
    TZ: America/Los_Angeles
  service:
    main:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      ports:
        http:
          port: 32400
  envFrom:
    - secretRef:
        name: plex-secret
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod  
        hajimari.io/enable: 'true'
        hajimari.io/icon: plex
        hajimari.io/appName: Plex
        hajimari.io/info: Stream movies and tv
      ingressClassName: nginx
      hosts:
        - host: &host plex.toolstowelsandfroods.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"

  persistence:
    config:
      enabled: true
      strageClass: longhorn
      readOnly: false
    media:
      enabled: true
      type: nfs
      server: 192.168.1.89
      path: "/volume1/k3s/plex"
      mountPath: /media
      readOnly: true
