app-template:
  image:
    repository: ghcr.io/onedr0p/plex
    tag: 1.30.2.6563-3d4dc0cce@sha256:d0d3e5e75f5ed86843d123cd84bb1f54a0593ec26c908410548862607af880bf
  controller:
    replicas: 1
    type: statefulset
  env:
    TZ: America/Los_Angeles
  service:
    main:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      ports:
        http:
          port: 32400
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/enable: 'true'
          hajimari.io/icon: plex
          hajimari.io/appName: Plex
          hajimari.io/info: Stream movies and tv
        ingressClassName: nginx
  podSecurityContext:
    runAsUser: 1028
    runAsGroup: 100
    fsGroup: 100
    fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      config:
        enabled: true
        storageClass: longhorn
      media:
        enabled: true
        mountPath: /storage/media
        existingClaim: plex-media-pvc

