apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-secret
  namespace: plex
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: plex-secret
    creationPolicy: Owner
  data:
    - secretKey: PLEX_CLAIM
      remoteRef:
        key: /plex
        property: PLEX_CLAIM
