app-template:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
    type: statefulset
    replicas: 1
  image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 1.12.2
  env:
    COMPOSE_PROJECT_NAME: paperless
    PAPERLESS_CONSUMER_POLLING: "60"
    PAPERLESS_CONSUMER_RECURSIVE: "true"
    PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
    PAPERLESS_OCR_LANGUAGES: eng
    PAPERLESS_OCR_LANGUAGE: eng
    PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
    PAPERLESS_PORT: 8000
    PAPERLESS_REDIS: redis://redis.redis.svc.cluster.local:6379
    PAPERLESS_TIKA_ENABLED: 1
    PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg.gotenberg.svc.cluster.local:3000
    PAPERLESS_TIKA_ENDPOINT: http://tika.tika.svc.cluster.local:9998
    PAPERLESS_TASK_WORKERS: 2
    PAPERLESS_TIME_ZONE: "America/Los_Angeles"
    PAPERLESS_CONSUMPTION_DIR: /mnt/inbox
    PAPERLESS_MEDIA_ROOT: /mnt/paperless
    USERMAP_UID: 1000
    USERMAP_GID: 1000
    PAPERLESS_ADMIN_USER: paperless_admin
  envFrom:
    - secretRef:
        name: paperless-secrets

  service:
    main:
      ports:
        http:
          port: 8000

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod     
        hajimari.io/enable: "true"
        hajimari.io/icon: file-document
        hajimari.io/appName: Paperless
        hajimari.io/info: Document management system that transforms your physical documents into a searchable online archive
      hosts:
       - host: &host paperless.toolstowelsandfroods.com
         paths:
           - path: /
             pathType: Prefix
      tls:
        - secretName: paperless-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"

  persistence:
    data:
      storageClass: longhorn
      mountPath: /usr/src/paperless/data
    media:
      enabled: true
      mountPath: /mnt/paperless
      existingClaim: paperless-media-pvc
    inbox:
      enabled: true
      mountPath: /mnt/inbox
      existingClaim: paperless-consume-pvc

  resources:
    requests:
      cpu: 23m
      memory: 2975M
    limits:
      memory: 6572M
