app-template:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
    type: statefulset
    replicas: 1
  image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 1.12.2
  env:
    COMPOSE_PROJECT_NAME: paperless
    PAPERLESS_CONSUMER_POLLING: "60"
    PAPERLESS_CONSUMER_RECURSIVE: "true"
    PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
    PAPERLESS_OCR_LANGUAGES: eng
    PAPERLESS_OCR_LANGUAGE: eng
    PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
    PAPERLESS_PORT: 8000
    PAPERLESS_REDIS: redis://localhost:6379
    PAPERLESS_TIKA_ENABLED: 1
    PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
    PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
    PAPERLESS_TASK_WORKERS: 2
    PAPERLESS_TIME_ZONE: "America/Los_Angeles"
    PAPERLESS_URL: https://paperless.toostowelsandfroods.com
    PAPERLESS_CONSUMPTION_DIR: /usr/src/paperless/consume
    PAPERLESS_MEDIA_ROOT: /usr/src/paperless/media
    USERMAP_UID: 1000
    USERMAP_GID: 1000
    PAPERLESS_ADMIN_USER: paperless_admin
  envFrom:
    - secretRef:
        name: paperless-secrets
  service:
    main:
      ports:
        http:
          port: 8000
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: file-document
        hajimari.io/appName: Paperless
        hajimari.io/info: Document management system that transforms your physical documents into a searchable online archive
      hosts:
       - host: &host paperless.toolstowelsandfroods.com
         paths:
           - path: /
             pathType: Prefix
      tls:
        - secretName: paperless-tls-certificate
          hosts:
            - *host        
  podSecurityContext:
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  persistence:
    data:
      enabled: true
      storageClass: longhorn
    media:
      enabled: true
      mountPath: /usr/src/paperless/media
      type: nfs
      server: 192.168.1.89
      path: "/volume1/k3s/paperless/media"
    consume:
      enabled: true
      mountPath: /usr/src/paperless/consume
      type: nfs
      server: 192.168.1.89
      path: "/volume1/k3s/paperless/consume"
    export:
      enabled: true
      mountPath: /usr/src/paperless/export
      type: nfs
      server: 192.168.1.89
      path: "/volume1/k3s/paperless/export"
  sidecars:
    redis:
      name: redis
      image: redis:7.0
      imagePullPolicy: IfNotPresent
    gotenburg:
      name: gotenburg
      image: thecodingmachine/gotenberg:7.8.0
      env:
        - name: DISABLE_GOOGLE_CHROME
          value: '1'
    tika:
      image: apache/tika:2.5.0
      name: tika
      imagePullPolicy: Always
  resources:
    requests:
      cpu: 23m
      memory: 2975M
    limits:
      memory: 6572M
