apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recipes-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: recipes-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: /recipes/
        property: secret-key
    - secretKey: db-password
      remoteRef:
        key: /recipes/
        property: db-password
    - secretKey: postgres-user-password
      remoteRef:
        key: /recipes/
        property: postgres-user-password

