apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
data:
  config.yaml: |-
    theme: auto
    default_2fa_method: totp
    storage:
      local:
        path: /db/db.sqlite3
    authentication_backend:
      password_reset:
        disable: true
      ldap:
        implementation: custom
        url: ldap://lldap.lldap.svc.cluster.local:3890
        timeout: 5s
        start_tls: false
        base_dn: dc=home
        additional_users_dn: OU=users
        users_filter: (&({username_attribute}={input})(objectClass=posixAccount))
        username_attribute: uid
        mail_attribute: mail
        display_name_attribute: givenName
        groups_filter: (&(memberUid={username})(objectClass=posixGroup))
        group_name_attribute: cn
        user: admin

    access_control:
      default_policy: one_factor
      networks:
        - name: internal
          networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
    session:
      redis:
        host: redis.redis.svc.cluster.local
    notifier:
      disable_startup_check: false
      filesystem:
        filename: /config/notification.txt

    server:
      port: 80

    telemetry:
      metrics:
        enabled: true
        address: "tcp://0.0.0.0:8080"
