apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: authelia-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTHELIA_JWT_SECRET
      remoteRef:
        key: /authelia/
        property: jwt_secret
    - secretKey: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
      remoteRef:
        key: /ldap/
        property: LLDAP_LDAP_USER_PASS
    - secretKey: AUTHELIA_STORAGE_ENCRYPTION_KEY
      remoteRef:
        key: /authelia/
        property: encryption_key
    - secretKey: AUTHELIA_SESSION_SECRET
      remoteRef:
        key: /authelia/
        property: session_secret
    - secretKey: AUTHELIA_NOTIFIER_SMTP_PASSWORD
      remoteRef:
        key: /authelia/
        property: smtp_password
    - secretKey: AUTHELIA_NOTIFIER_SMTP_USERNAME
      remoteRef:
        key: /authelia/
        property: username
    - secretKey: AUTHELIA_NOTIFIER_SMTP_SENDER
      remoteRef:
        key: /authelia/
        property: smtp_sender
    - secretKey: IMMICH_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /authelia/
        property: IMMICH_OAUTH_CLIENT_SECRET

    

