apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: authelia-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /authelia/
        property: jwt_secret
    - secretKey: password
      remoteRef: AUTHENTICATION_BACKEND_LDAP_PASSWORD
        key: /ldap/
        property: LLDAP_LDAP_USER_PASS
    - secretKey: STORAGE_ENCRYPTION_KEY
      remoteRef:
        key: /authelia/
        property: encryption_key
    - secretKey: SESSION_SECRET
      remoteRef:
        key: /authelia/
        property: session_secret

