pod-gateway:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"

  image:
    repository: ghcr.io/angelnu/pod-gateway
    tag: v1.8.1

  addons:
    vpn:
      enabled: true
      type: gluetun
      image:
        repository: docker.io/qmcgaw/gluetun
        tag: v3.32.0
      env:
        - name: VPN_SERVICE_PROVIDER
          value: nordvpn
        - name: SERVER_REGIONS
          value: California
      envFrom:
        - secretRef:
            name: nordvpn-secrets
      networkPolicy:
        enabled: true
        egress:
          - ports:
            - port: 51820
              protocol: UDP
            to:
            - ipBlock:
                cidr: 0.0.0.0/0
          - to:
            - ipBlock:
                cidr: 10.0.0.0/8
      securityContext:
        capabilities:
          add:
            - NET_ADMIN

    netshoot:
      enabled: true

  publicPorts:
    - IP: 10
      hostname: qbittorrent-0
      ports:
        - port: 57464
          type: udp
        - port: 57464
          type: tcp

  routed_namespaces:
    - media

  settings:
    VPN_INTERFACE: "wg0"
    VXLAN_ID: "43"
    VXLAN_IP_NETWORK: "172.16.1"
    VPN_BLOCK_OTHER_TRAFFIC: "true"
    VPN_TRAFFIC_PORT: "51820"
    DNS_LOCAL_CIDRS: "local"
    NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
    VPN_LOCAL_CIDRS: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
    IPTABLES_NFT: "yes"
  webhook:
    gatewayDefault: false
    image:
      repository: ghcr.io/angelnu/gateway-admision-controller
      tag: v3.7.0
