pod-gateway:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"

  image:
    repository: ghcr.io/angelnu/pod-gateway
    tag: v1.8.1
  DNS: 172.16.1.1
  addons:
    vpn:
      enabled: true
      type: gluetun
      image:
        repository: ghcr.io/qdm12/gluetun
        tag: v3.34.3
      env:
        - name: VPN_SERVICE_PROVIDER
          value: nordvpn
        - name: VPN_INTERFACE
          value: wg0
        - name: FIREWALL
          value: "off"
        - name: DOT
          value: "off"
        - name: SERVER_REGIONS
          value: California
        - name: LOG_LEVEL
          value: debug
      envFrom:
        - secretRef:
            name: nordvpn-secrets
    netshoot:
      enabled: true

  publicPorts:
    - IP: 10
      hostname: qbittorrent-0
      ports:
        - port: 57464
          type: udp
        - port: 57464
          type: tcp
  settings:
    NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
    VPN_BLOCK_OTHER_TRAFFIC: true
    VPN_INTERFACE: wg0
    VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
    VPN_TRAFFIC_PORT: "51820"
    VXLAN_ID: 43
    VXLAN_IP_NETWORK: 172.16.1

  routed_namespaces:
    - media
  webhook:
    gatewayDefault: false
    image:
      repository: ghcr.io/angelnu/gateway-admision-controller
      tag: v3.7.0
