---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: immich
data:
  DB_DATABASE_NAME: immich
  DB_HOSTNAME: localhost
  DB_USERNAME: immich
  DB_PORT: "5432"
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  REDIS_HOSTNAME: localhost
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "10"
  TYPESENSE_HOST: localhost
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  TYPESENSE_DATA_DIR: /config
  IMMICH_WEB_URL: http://localhost:3000
  IMMICH_SERVER_URL: http://localhost:3001
  IMMICH_MACHINE_LEARNING_URL: http://localhost:3003
