---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx-consume-pv
  namespace: paperless
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.89
    path: "/volume1/paperless/consume"
