---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx-data-pv
  namespace: paperless
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.89
    path: "/volume1/paperless/data"
