---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx-static-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.1.89
    path: "/volume1/paperless"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
  namespace: paperless
spec:
  volumeName: paperless-ngx-static-pv
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
