apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secret-key
  namespace: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        username: paperless-ngx
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: /paperless-ngx
        property: secret_key

