apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: paperless-secrets
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: /paperless-ngx/db
        property: password
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: /paperless-ngx
        property: secret_key
