immich:
  repository:
    name: immich-charts
    url: https://github.com/immich-app/immich-charts
  common_env:
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: immich-secrets
          key: DB_PASSWORD          
    JWT_SECRET:
      valueFrom:
        secretKeyRef:
          name: immich-secrets
          key: JWT_SECRET
    DB_HOSTNAME: &dbhost postgres-rw.cloudnative-pg.svc.cluster.local
  service:
    main:
      enabled: true
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hajimari.io/appName: "Immich"
        hajimari.io/icon: heroicons:photo
      hosts:
        - host: &host photos.toolstowelsandfroods.com
          paths:
            - path: /
              backend:
                service:
                  name: immich-proxy
                  port:
                    number: 8080
      tls:
        - secretName: immich-tls-certificate
          hosts:
            - *host
  redis:
    enabled: true
  postgresql:
    enabled: false
  server:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.6
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_HOST
            value: postgres-rw.cloudnative-pg.svc.cluster.local
          - name: POSTGRES_DB
            value: immich
          - name: POSTGRES_USER
            value: immich
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: immich-secrets
                key: DB_PASSWORD
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: immich-secrets
                key: POSTGRES_SUPER_PASS
          - name: POSTGRES_SUPER_USER
            valueFrom:
              secretKeyRef:
                name: immich-secrets
                key: POSTGRES_SUPER_USER
                
  persistence:
    library:
      enabled: true
      existingClaim: immich-nfs
      mountPath: /usr/src/app/upload
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      memory: 6000Mi

