app-template:
  name: &app immich
  namespace: immich
  image:
    repository: ghcr.io/immich-app/immich-proxy
    tag: v1.51.2
  envFrom:
    - secretRef:
        name: immich-secrets
    - configMapRef:
        name: immich-configmap
  service:
    main:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      externalIPs: ["192.168.50.225","192.168.50.226","192.168.50.227","192.168.50.228"]
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hajimari.io/appName: "Immich"
        hajimari.io/icon: heroicons:photo
      hosts:
        - host: &host photos.toolstowelsandfroods.com
          paths:
            - path: /
      tls:
        - hosts:
            - *host
  persistence:
    library:
      enabled: true
      existingClaim: immich-nfs
      mountPath: /usr/src/app/upload
    config:
      enabled: true
      existingClaim: immich-nfs
      mountPath: /config
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      memory: 2000Mi
  sidecars:
    immich-server:
      name: immich-server
      image: ghcr.io/immich-app/immich-server:v1.51.2
      volumeMounts:
        - name: library
          mountPath: /usr/src/app/upload
      command: ["/bin/sh"]
      args:
        - ./start-server.sh
      envFrom:
        - secretRef:
            name: immich-secrets
        - configMapRef:
            name: immich-configmap
    immich-microservices:
      name: immich-microservices
      image: ghcr.io/immich-app/immich-server:v1.51.2
      volumeMounts:
        - name: library
          mountPath: /usr/src/app/upload
      command: ["/bin/sh"]
      args:
        - ./start-microservices.sh
      envFrom:
      - secretRef:
          name: immich-secrets
      - configMapRef:
          name: immich-configmap
    immich-redis:
      name: immich-redis
      image: public.ecr.aws/docker/library/redis:7.0.8
      env:
        - name: REDIS_REPLICATION_MODE
          value: master
      envFrom:
      - configMapRef:
          name: immich-configmap
      command: ["redis-server"]
    immich-web:
      name: immich-web
      image: ghcr.io/immich-app/immich-web:v1.51.2
      volumeMounts:
        - name: library
          mountPath: /usr/src/app/upload
      command: ["/bin/sh"]
      args:
        - ./entrypoint.sh
      envFrom:
      - secretRef:
          name: immich-secrets
      - configMapRef:
          name: immich-configmap
    immich-machinelearning:
      name: immich-machinelearning
      image: ghcr.io/immich-app/immich-machine-learning:v1.51.2
      volumeMounts:
        - name: library
          mountPath: /usr/src/app/upload
      envFrom:
      - secretRef:
          name: immich-secrets
      - configMapRef:
          name: immich-configmap
    immich-db:
      name: immich-db
      image: postgres:15
      env:
        POSTGRES_USER: immich
        POSTGRES_DB: immich
      envFrom:
      - secretRef:
          name: immich-secrets
    immich-typesense:
      name: immich-typesense
      image: typesense/typesense:0.24.0
      envFrom:
      - secretRef:
          name: immich-secrets
      - configMapRef:
          name: immich-configmap
      volumeMounts:
        - name: config
          mountPath: /config
# resources:
#   requests:
#     cpu: 23m
#     memory: 2975M
#   limits:
#     memory: 6572M
