app-template:
  domain: toolstowelsandfroods.com
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
    type: statefulset
  image:
    repository: ghcr.io/authelia/authelia
    # TODO Switch to Authelia release tag on next release
    tag: master@sha256:9ec88ac73269855f3a0e0b80ed6ee4980decd81fb12901ff39cd9d8d2cf9b6fc
  args: ["--config", "/etc/authelia/config.yaml"]
  service:
.    main:
      ports:
        http:
          port: &port 80
        metrics:
          enabled: true
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: lock
        hajimari.io/appName: Authelia
        hajimari.io/info: Authentication and authorization, MFA and SSO
      hosts:
        - host: &host auth.toolstowelsandfroods.com
          paths:
            - path: /

      tls:
        - secretName: authelia-tls-certificate
          hosts:
            - *host
  env:
  - name: TZ
    value: America/Los_Angeles
  envFrom:
    - secretRef:
        name: authelia-secrets
  enableServiceLinks: false
  resources:
    requests:
      cpu: "0.25"
      memory: 50Mi
    limits:
      cpu: "4.00"
      memory: 120Mi
  rbac:
    enabled: true
  secret:
    existingSecret: authelia-secrets
  persistence:
    config:
      enabled: true
      type: configMap
      name: authelia-config
      subPath: config.yaml
      mountPath: /etc/authelia/config.yaml
      readOnly: false
