app-template:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
    type: statefulset
  image:
    repository: ghcr.io/authelia/authelia
    # TODO Switch to Authelia release tag on next release
    tag: master@sha256:cc12c2b96ea0af84782ca740ea30d45582c5d801be4633aefc8565ccb4172f87
  args: ["--config", "/config/configuration.yml", "--config.experimental.filters", "expand-env"]
  env:
    TZ: America/Los_Angeles
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_GROUPS_DN: ou=groups
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_USERS_DN: ou=people
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: dc=toolstowelsandfroods,dc=homearpa
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_DISPLAY_NAME_ATTRIBUTE: displayName
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUPS_FILTER: (member={dn})
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUP_NAME_ATTRIBUTE: cn
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_IMPLEMENTATION: custom
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_MAIL_ATTRIBUTE: mail
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_START_TLS: "false"
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TIMEOUT: 5s
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_URL: ldap://lldap.lldap.svc.cluster.local:3890
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: uid=admin,ou=people,dc=home,dc=arpa
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERNAME_ATTRIBUTE: uid
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERS_FILTER: (&({username_attribute}={input})(objectClass=person))
    AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_RESET_DISABLE: "true"
    AUTHELIA_AUTHENTICATION_BACKEND_REFRESH_INTERVAL: 1m
    AUTHELIA_DEFAULT_REDIRECTION_URL: https://auth.toolstowelsandfroods.com
    AUTHELIA_DUO_API_DISABLE: "true"
    AUTHELIA_LOG_LEVEL: info
    AUTHELIA_SERVER_DISABLE_HEALTHCHECK: "true"
    AUTHELIA_SERVER_PORT: &port 80
    AUTHELIA_SESSION_DOMAIN: toolstowelsandfroods.com
    AUTHELIA_SESSION_NAME: authelia-home-ops
    AUTHELIA_SESSION_REDIS_DATABASE_INDEX: 14
    AUTHELIA_SESSION_REDIS_HOST: redis.redis.svc.cluster.local
    AUTHELIA_TELEMETRY_METRICS_ADDRESS: tcp://0.0.0.0:8080
    AUTHELIA_TELEMETRY_METRICS_ENABLED: "true"
    AUTHELIA_THEME: dark
    AUTHELIA_TOTP_ISSUER: authelia.com
    AUTHELIA_WEBAUTHN_DISABLE: "true"
  enableServiceLinks: false
  service:
    main:
      ports:
        http:
          port: &port 80
        metrics:
          enabled: true
          port: 8080
  probes:
    liveness: &probes
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /api/health
          port: *port
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
    readiness: *probes
    startup:
      enabled: false
  serviceMonitor:
    main:
      enabled: true
      endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 1m
          scrapeTimeout: 10s
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: lock
        hajimari.io/appName: Authelia
        hajimari.io/info: Authentication and authorization, MFA and SSO
      hosts:
        - host: &host auth.toolstowelsandfroods.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: authelia-tls-certificate
          hosts:
          - *host
  domain: auth.toolstowelsandfroods.com
  password:
    external:
      name: authelia-secrets
      key: bind_password

  jwt_secret:
    external:
      name: authelia-secrets
      key: jwt_secret
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  persistence:
    config:
      enabled: true
      type: configMap
      name: authelia-configmap
      subPath: configuration.yml
      mountPath: /config/configuration.yml
      readOnly: false
    db:
      enabled: true
      existingClaim: authelia
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
    limits:
      memory: 1000Mi
