app-template:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
    type: statefulset
  image:
    repository: ghcr.io/authelia/authelia
    # TODO Switch to Authelia release tag on next release
    tag: master@sha256:cc12c2b96ea0af84782ca740ea30d45582c5d801be4633aefc8565ccb4172f87
  args: ["--config", "/etc/authelia/config.yaml"]
  env:
    TZ: America/Los_Angeles
  envFrom:
    - secretRef:
        name: authelia-secrets
  enableServiceLinks: false
  service:
    main:
      ports:
        http:
          port: &port 80
        metrics:
          enabled: true
          port: 8080
  probes:
    liveness: &probes
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /api/health
          port: *port
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
    readiness: *probes
    startup:
      enabled: false
  serviceMonitor:
    main:
      enabled: true
      endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 1m
          scrapeTimeout: 10s
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: lock
        hajimari.io/appName: Authelia
        hajimari.io/info: Authentication and authorization, MFA and SSO
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.default.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.example.com?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Method $request_method;
      hosts:
        - host: &host auth.toolstowelsandfroods.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: authelia-tls-certificate
          hosts:
          - *host
  domain: auth.toolstowelsandfroods.com
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  persistence:
    config:
      enabled: true
      type: configMap
      name: authelia-config
      subPath: config.yaml
      mountPath: /etc/authelia/config.yaml
      readOnly: false
    db:
      enabled: true
      existingClaim: authelia
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
    limits:
      memory: 1000Mi
