authelia:
  env:
    TZ: America/Los_Angeles

  # Authelia configuration
  domain: auth.toolstowelsandfroods.com

  # LDAP configuration
  authentication_backend:
    ldap:
      host: lldap.toolstowelsandfroods.com
      port: 389
      bind_dn: cn=admin,dc=toolstowelsandfroods,dc=com
      base_dn: dc=toolstowelsandfroods,dc=com
      bind_password:
        external:
          name: authelia-secrets
          key: bind_password
      user_search_base: ou=users,dc=toolstowelsandfroods,dc=com
      user_search_filter: "(uid={0})"
      group_search_base: ou=groups,dc=toolstowelsandfroods,dc=com

jwt_secret:
    external:
      name: authelia-secrets
      key: jwt_secret

  probes:
    liveness: &probes
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /api/health
          port: *port
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
    readiness: *probes
    startup:
      enabled: false
  serviceMonitor:
    main:
      enabled: true
      endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 1m
          scrapeTimeout: 10s
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: lock
        hajimari.io/appName: Authelia
        hajimari.io/info: Authentication and authorization, MFA and SSO
      hosts:
        - host: &host auth.toolstowelsandfroods.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: authelia-tls-certificate
          hosts:
          - *host
  # Enable persistence using PersistentVolumeClaim
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: longhorn
    accessMode: ReadWriteOnce

  # Expose Authelia using a LoadBalancer service
  service:
    enabled: true
    type: LoadBalancer
    port: 8080
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

  resources:
    requests:
      cpu: 5m
      memory: 10Mi
    limits:
      memory: 200Mi
