app-template:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2023-03-13T19-46-17Z
  env:
    TZ: America/Los_Angeles
    MINIO_UPDATE: "off"
    MINIO_BROWSER_REDIRECT_URL: https://minio.toolstowelsandfroods.com
  envFrom:
    - secretRef:
        name: minio-secrets
  args: ["server", "/data", "--console-address", ":9001"]
  service:
    main:
      enabled: true
      ports:
        http:
          port: 9001
        api:
          enabled: true
          port: 9000
  probes:
    liveness: &probes
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /minio/health/live
          port: 9000
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
    readiness: *probes
    startup:
      enabled: false
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: bucket
        hajimari.io/appName: MinIO
        hajimari.io/info: MinIO offers high-performance, S3 compatible object storage
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
       - host: &host minio.toolstowelsandfroods.com
         paths:
           - path: /
             pathType: Prefix
      tls:
        - secretName: minio-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  persistence:
    config:
      enabled: true
      mountPath: /data
      type: nfs
      server: 192.168.1.89
      path: "/volume1/k3s/backups"
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 750Mi
