cloudnative-pg:
  crds:
    create: true
  service:
    main:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.50.230
      ports:
        - name: postgres
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        postgresql: postgres
        role: primary
