apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-secret
  namespace: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: lldap-secret
    creationPolicy: Owner
  data:
    - secretKey: bind_password
      remoteRef:
        key: /ldap/
        property: bind_password

