apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cloudnative-pg-secrets
  data:
    - secretKey: POSTGRES_SUPER_USER
      remoteRef:
        key: /cloudnative-pg/
        property: POSTGRES_SUPER_USER
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: /cloudnative-pg/
        property: POSTGRES_SUPER_PASS
