app-template:
  controller:
    type: statefulset
    replicas: 1
  image:
    repository: homeassistant/home-assistant
    tag: 2023.12.4
    pullPolicy: IfNotPresent
  strategy:
    type: Recreate
  env:
    TZ: America/Los_Angeles
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    main:
      type: LoadBalancer
      externalIPs: ["192.168.50.225","192.168.50.226","192.168.50.227"]
      externalTrafficPolicy: Local
      ports:
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - 192.168.50.11
            - 192.168.50.12
            - 192.168.50.0/24
          port: 8123

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: home-assistant
        hajimari.io/appName: Home Assistant
        hajimari.io/info: Home automation that puts local control and privacy first
      hosts:
        - host: &host ha.toolstowelsandfroods.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: home-assistant-tls-certificate
          hosts:
            - *host
        
  persistence:
    config:
      enabled: true
      storageClass: longhorn

  resources:
    limits:
      memory: 3000Mi
    requests:
      cpu: 100m
      memory: 1000Mi

  addons:
    codeserver:
      enabled: true
      image:
        repository: ghcr.io/coder/code-server
        tag: 4.22.0
      env:
        TZ: America/Los_Angeles
      workingDir: /config
      args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/appName: "HASS Config"
          hajimari.io/icon: cib:visual-studio-code
          hajimari.io/enable: "true"
          hajimari.io/info: VS Code for HASS configuration editing
        hosts:
          - host: &host hassconfig.toolstowelsandfroods.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: hassconfig-tls-certificate
            hosts:
              - *host
  
      volumeMounts:
        - name: config
          mountPath: /config
