apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media-pvc
spec:
  volumeName: paperless-media-pv
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
