apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: paperless-secrets
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: /paperless/
        property: PAPERLESS_ADMIN_PASSWORD
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: /paperless/
        property: PAPERLESS_SECRET_KEY
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: /paperless/
        property: POSTGRES_SUPER_PASS
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /paperless/
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: /paperless/
        property: POSTGRES_PASS
