app-template:
  controller:
    replicas: 1
    type: statefulset
  image:
    repository: ghcr.io/onedr0p/readarr-nightly
    tag: 0.3.21.2457@sha256:32d28a20d5b034633b0a605662a0d68af5e209c6d1226a084ce1ee29531596d3
  env:
    TZ: America/Los_Angeles
    READARR__INSTANCE_NAME: Readarr
    READARR__PORT: &port 80
    READARR__LOG_LEVEL: info
  service:
    main:
      ports:
        http:
          port: *port
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: book-open-variant
        hajimari.io/appName: Readarr
        hajimari.io/info: Ebook collection manager for Usenet and BitTorrent users
      hosts:
       - host: &host books.toolstowelsandfroods.com
         paths:
           - path: /
             pathType: Prefix
      tls:
        - secretName: readarr-tls-certificate
          hosts:
            - *host  
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteMany
      size: 1Gi
    media:
      enabled: true
      type: nfs
      server: 192.168.1.89
      path: /volume1/k3s/data
      mountPath: /media
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
    limits:
      memory: 750Mi
