apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: longhorn-recurring-backup
  namespace: longhorn-system
spec:
  cron: "*/30 * * * *"
  task: "backup"
  groups:
  - default
  retain: 6
  concurrency: 2
