apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: longhorn-recurring-snapshot
  namespace: longhorn-system
spec:
  cron: "*/10 * * * *"
  task: "snapshot"
  groups:
  - default
  retain: 6
  concurrency: 2
