apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: immich-secrets
  data:
    # Immich
    DB_DATABASE_NAME: &dbname immich
    DB_HOSTNAME: &dbhost postgres-rw.default.svc.cluster.local
    - secretKey: DB_USERNAME
      remoteRef:
        key: /immich/
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /immich/
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: /immich/
        property: JWT_SECRET
    # Postgres Init
    POSTGRES_DB: *dbname
    POSTGRES_HOST: *dbhost
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: /immich/
        property: DB_PASSWORD
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: /immich/
        property: POSTGRES_SUPER_PASS
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /immich/
        property: DB_USERNAME

