apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: immich-secrets
  data:
    # Immich
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /immich/
        property: DB_PASSWORD
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /immich/
        property: DB_PASSWORD
    - secretKey: POSTGRES_POSTGRES_PASSWORD
      remoteRef:
        key: /immich/
        property: POSTGRES_SUPER_PASS
    - secretKey: JWT_SECRET
      remoteRef:
        key: /immich/
        property: JWT_SECRET
    - secretKey: TYPESENSE_API_KEY
      remoteRef:
        key: /immich/
        property: TYPESENSE_API_KEY
    # Postgres Init
    - secretKey: postgres-password
      remoteRef:
        key: /immich/
        property: POSTGRES_PASSWORD
    - secretKey: password
      remoteRef:
        key: /immich/
        property: DB_PASSWORD
    - secretKey: postgres-postgres-password
      remoteRef:
        key: /immich/
        property: POSTGRES_SUPER_PASS


