apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: immich-secrets
  data:
    # Immich
    - secretKey: DB_USERNAME
      remoteRef:
        key: /immich/
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /immich/
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: /immich/
        property: JWT_SECRET
    # Postgres Init
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: /immich/
        property: DB_PASSWORD
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: /cloudnative-pg/
        property: POSTGRES_SUPER_PASS
    - secretKey: POSTGRES_SUPER_USER
      remoteRef:
        key: /cloudnative-pg/
        property: POSTGRES_SUPER_USER
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /immich/
        property: DB_USERNAME

