apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: immich-secrets
  data:
    # Immich
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /immich/
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: /immich/
        property: JWT_SECRET

