apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: immich-secrets
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: /immich
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /immich
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: /immich
        property: JWT_SECRET
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: /immich
        property: POSTGRES_SUPER_PASS
