app-template:
  controller:
    type: statefulset
    replicas: 1
  image:
    repository: homeassistant/home-assistant
    tag: 2023.2.5
    pullPolicy: IfNotPresent
  strategy:
    type: Recreate
  env:
    TZ: America/Los_Angeles
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    main:
      ports:
        http:
          port: 8123
        mdns-tcp:
          enabled: true
          port: 5353
          protocol: TCP
          targetPort: 5353
        mdns-udp:
          enabled: true
          port: 5353
          protocol: UDP
          targetPort: 5353

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: home-assistant
        hajimari.io/appName: Home Assistant
        hajimari.io/info: Home automation that puts local control and privacy first
        
  persistence:
    config:
      enabled: true
      storageClass: longhorn

  resources:
    limits:
      memory: 3000Mi
    requests:
      cpu: 100m
      memory: 1000Mi

  addons:
    codeserver:
      enabled: true
      image:
        repository: ghcr.io/coder/code-server
        tag: 4.10.0
      env:
        TZ: America/Los_Angeles
      workingDir: /config
      args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: "HASS Config"
          hajimari.io/icon: cib:visual-studio-code
          hajimari.io/enable: "true"
          hajimari.io/info: VS Code for HASS configuration editing
  
      volumeMounts:
        - name: config
          mountPath: /config
