apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: minio-secrets
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: /minio/
        property: MINIO_ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: /minio/
        property: MINIO_ROOT_PASSWORD
