app-template:
  controller:
    replicas: 1
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
  image:
    repository: ghcr.io/onedr0p/prowlarr-develop
    tag: 1.5.2.3484
  env:
    TZ: America/Los_Angeles
    PROWLARR__INSTANCE_NAME: Prowlarr
    PROWLARR__PORT: &port 80
    PROWLARR__LOG_LEVEL: info
  envFrom:
    - secretRef:
        name: prowlarr-secret
  service:
    main:
      ports:
        http:
          port: *port
  podAnnotations:
    setGateway: "true"
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: movie-search
        hajimari.io/appName: Prowlarr
        hajimari.io/info: Indexer manager/proxy built on the popular *arr .net/reactjs base stack
      hosts:
       - host: &host prowlarr.toolstowelsandfroods.com
         paths:
           - path: /
             pathType: Prefix
      tls:
        - secretName: radarr-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteMany
      size: 1Gi
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 500Mi
