apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  annotations:
    argocd.argoproj.io/sync-wave: "101"
spec:
  destination:
    namespace: uptime-kuma
    server: "https://kubernetes.default.svc"
  source:
    chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 1.3.2
    helm:
      values: |-
        image:
          repository: louislam/uptime-kuma
          tag: 1.17.1
          pullPolicy: IfNotPresent
        env:
          TZ: America/Los_Angeles
          UPTIME_KUMA_PORT: "3001"
          UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: "0"
        service:
          main:
            ports:
              http:
                port: 3001
        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            pathType: Prefix
            annotations:
              nginx.ingress.kubernetes.io/configuration-snippet: |
                proxy_set_header Accept-Encoding "";
                sub_filter
                '</head>'
                '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/uptime-kuma/nord.css">
                </head>';
                sub_filter_once on;
            hosts:
              - host: &host status.toolstowelsandfroods.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - *host
        persistence:
          data:
            enabled: true
            storageClass: longhorn
            size: 3Gi
            mountPath: /app/data
            accessMode: ReadWriteOnce
