app-template:
  controller:
    replicas: 1
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
  image:
    repository: ghcr.io/onedr0p/sabnzbd
    tag: 4.2.3@sha256:fa8ddea45e56b0e36454c3c0eb30ff5521d90aeb5b35301656ae9236680be3a9
  env:
    TZ: America/Los_Angeles
    SABNZBD__PORT: &port 80
  envFrom:
    - secretRef:
        name: sabnzbd-secret
  service:
    main:
      ports:
        http:
          port: *port
  probes:
    liveness: &probes
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /api?mode=version
          port: *port
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
    readiness: *probes
    startup:
      enabled: false
  podAnnotations:
    setGateway: "true"
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: download
        hajimari.io/appName: SABnzbd
        hajimari.io/info: Free and easy binary newsreader
      hosts:
       - host: &host sabnzbd.toolstowelsandfroods.com
         paths:
           - path: /
             pathType: Prefix
      tls:
        - secretName: sabnzbd-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteMany
      size: 1Gi
    media:
      enabled: true
      type: nfs
      server: 192.168.1.89
      path: /volume1/k3s/data
      mountPath: /media
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
    limits:
      memory: 6000Mi

