app-template:
  controller:
    type: statefulset
    replicas: 1
  image:
    repository: ghcr.io/hay-kot/homebox
    tag: latest
    pullPolicy: Always
  env:
    TZ: America/Los_Angeles
    HBOX_LOG_LEVEL: info
    HBOX_LOG_FORMAT: text
    HBOX_WEB_MAX_UPLOAD_SIZE: 10
  service:
    main:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      externalIPs: ["192.168.50.225"]
      ports:
        http:
          port: 7745
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'true'
        hajimari.io/icon: box
        hajimari.io/appName: Homebox
        hajimari.io/group: Documents
        hajimari.io/info: Inventory and organization
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.authelia.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.toolstowelsandfroods.com?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      ingressClassName: nginx
      hosts:
        - host: &host org.toolstowelsandfroods.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homebox-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      storageClass: longhorn
      mountPath: /data
      accessMode : ReadWriteMany
      size: 10Gi
