pod-gateway:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"

  image:
    repository: ghcr.io/angelnu/pod-gateway
    tag: v1.10.0
  DNS: 172.16.1.1
  addons:
    vpn:
      enabled: true
      type: gluetun
      image:
        repository: ghcr.io/qdm12/gluetun
        tag: v3.37.0
      env:
        - name: VPN_SERVICE_PROVIDER
          value: nordvpn
        - name: VPN_INTERFACE
          value: tun0
        - name: SERVER_REGIONS
          value: United States
        - name: LOG_LEVEL
          value: debug
      envFrom:
        - secretRef:
            name: nordvpn-secrets
      networkPolicy:
        enabled: true
        egress:
          - ports:
            - port: 51820
              protocol: UDP
            to:
            - ipBlock:
                cidr: 0.0.0.0/0
          - to:
            - ipBlock:
                cidr: 10.0.0.0/8
      securityContext:
        capabilities:
          add:
            - NET_ADMIN 
    netshoot:
      enabled: true
      
  publicPorts:
    - IP: 10
      hostname: qbittorrent-0
      ports:
        - port: 57464
          type: udp
        - port: 57464
          type: tcp
  settings:
    NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
    VPN_INTERFACE: tun0
    VPN_BLOCK_OTHER_TRAFFIC: true
    VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
    VPN_TRAFFIC_PORT: "51820"
    VXLAN_ID: 43
    VXLAN_IP_NETWORK: 172.16.1

  routed_namespaces:
    - media
    - qbittorrent
    - prowlarr
    - sabnzbd
  webhook:
    gatewayDefault: false
    image:
      repository: ghcr.io/angelnu/gateway-admision-controller
      tag: v3.10.0

