app-template:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
    type: statefulset
    replicas: 1
  image:
    repository: docker.io/photoprism/photoprism
    tag: latest
  env:
    PHOTOPRISM_STORAGE_PATH: /photoprism/storage
    PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
    PHOTOPRISM_ORIGINALS_LIMIT: 10000 # in MB (default 1000)
  envFrom:
    - secretRef:
        name: photoprism-secrets
  persistence:
    config:
      enabled: true
      mountPath: /photoprism/storage
      type: nfs
      server: 192.168.1.89
      path: "/volume1/k3s/photoprism/storage"

    originals:
      enabled: true
      mountPath: "/photoprism/originals"
      type: nfs
      server: 192.168.1.89
      path: "/volume1/k3s/photoprism/originals"
  service:
    main:
      ports:
        http:
          port: 2342

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: arcticons:photoprism
        hajimari.io/info: Manage Photos
        hajimari.io/group: media
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
      hosts:
       - host: &host photoprism.toolstowelsandfroods.com
         paths:
           - path: /
             pathType: Prefix
      tls:
        - secretName: photoprism-tls-certificate
          hosts:
            - *host
