apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
    - name: nfs-container
      image: nginx
      volumeMounts:
        - name: nfs-volume
          mountPath: "/mnt/nfs"
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
      # Write to a file inside our NFS
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /mnt/nfs/dates.txt; sleep 5; done"] 
