apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: photoprism-secrets
  namespace: photoprism
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: photoprism-secrets
    creationPolicy: Owner
  data:
    - secretKey: PHOTOPRISM_ADMIN_PASSWORD
      remoteRef:
        key: /photoprism/
        property: PHOTOPRISM_ADMIN_PASSWORD
