apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: esphome-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |
          wifi_ssid: "{{ .esphome_wifi_ssid }}"
          wifi_pwd: "{{ .esphome_wifi_password }}"
  data:
    - secretKey: esphome_wifi_ssid
      remoteRef:
        key: /esphome/
        property: wifi_ssid
    - secretKey: esphome_wifi_password
      remoteRef:
        key: /esphome/
        property: wifi_password
