app-template:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
    type: statefulset
  image:
    repository: ghcr.io/actualbudget/actual-server
    tag: 23.3.2
    pullPolicy: Always
  env:
    TZ: America/Los_Angeles
  service:
    main:
      enabled: true
      ports:
        http:
          port: 5006
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hajimari.io/enable: 'true'
        hajimari.io/icon: piggy-bank
        hajimari.io/appName: Actual Budget
        hajimari.io/info: Personal finance

      hosts:
        - host: &host budget.toolstowelsandfroods.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: budget-tls-certificate
          hosts:
            - *host
    persistence:
      data:
        enabled: true
        mountPath: /data
        storageClass: longhorn
        accessMode: ReadWriteMany
        size: 2Gi
        retain: true
    resources:
      requests:
        cpu: 100m
        memory: 52M
      limits:
        memory: 256M
