photoprism:
  replicaCount: 1  
  config:
    PHOTOPRISM_ORIGINALS_LIMIT: 10000
  envFrom:
    - secretRef:
        name: photoprism-secrets
  persistence:
    enabled: true
    cachePath: &cachePath /assets/cache
    importPath: &importPath /assets/photos/import
    exportPath: &exportPath /assets/photos/export
    originalsPath: &originalsPath /assets/photos/originals
    volumeMounts:
    - name: originals
      mountPath: *originalsPath
      subPath: "media/photos"
    - name: photoprism
      mountPath: *cachePath
      subPath: "cache"
    - name: photoprism
      mountPath: *importPath
      subPath: "import"
    - name: photoprism
      mountPath: *exportPath
      subPath: "export"
    volumes:
    - name: originals
      nfs:
        server: 192.168.1.89
        path: "/volume1/k3s/photoprism/originals"
        readOnly: true     # PhotoPrism should not delete your originals, but just to be safe...
    # Photoprism-only share for storing image thumbnails, etc.
    - name: photoprism
      nfs:
        server: 192.168.1.89
        path: "volume1/k3s/photoprism/storage"

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: arcticons:photoprism
        hajimari.io/info: Manage Photos
        hajimari.io/group: media
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
      hosts:
       - host: &host photoprism.toolstowelsandfroods.com
         paths:
           - path: /
             pathType: Prefix
      tls:
        - secretName: photoprism-tls-certificate
          hosts:
            - *host
