apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: services
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: immich-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: /immich
        property: POSTGRES_SUPER_PASS
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /immich
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: /immich
        property: POSTGRES_PASS
    - secretKey: JWT_SECRET
      remoteRef:
        key: /immich
        property: JWT_SECRET
