apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nordvpn-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: nordvpn-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: /nordvpn/
        property: user
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: /nordvpn/
        property: password

