apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume-pvc
spec:
  volumeName: paperless-consume-pv
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
