---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-consume-pv
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.89
    path: "/volume1/k3s/paperless/consume"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-consume-pvc
spec:
  volumeName: paperless-consume-pv
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
