---
apiVersion: argoproj.io/v1alpha1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: argocd
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.12.2
    env:
      COMPOSE_PROJECT_NAME: paperless-ngx
      PAPERLESS_TIME_ZONE: America/Los_Angeles
      PAPERLESS_URL: http{{if ne ( len .Values.ingress.main.tls ) 0 }}s{{end}}://{{ (first .Values.ingress.main.hosts).host }}
      PAPERLESS_DBHOST: paperless-ngx-postgresql
      PAPERLESS_DBNAME: paperless-ngx
      PAPERLESS_DBUSER: paperless-ngx
      PAPERLESS_DBPASS: 
        existingSecret: paperless-ngx-db-secret
      PAPERLESS_REDIS: redis://paperless-ngx-redis-master:6379
      USERMAP_UID: 33
      USERMAP_GID: 33
      PAPERLESS_CONSUMPTION_DIR: /paperless/consume
      PAPERLESS_DATA_DIR: /paperless/data
      PAPERLESS_MEDIA_ROOT: /paperless/media
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
      PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: true
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_SECRET_KEY: 
        existingSecret: paperless-ngx-secret-key
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/appName: Paperless
          hajimari.io/icon: file-document
        hosts:
          - host: &host paperless.toolstowelsandfroods.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: paperless-tls-certificate
            hosts:
              - *host
     postgresql:
       enabled: true
