---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-media-pv
spec:
  capacity:
    storage: 50Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.89
    path: "/volume1/k3s/paperless/media"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-media-pvc
spec:
  volumeName: paperless-media-pv
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
