---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-postgresql
  namespace: paperless
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
