---
apiVersion: argoproj.io/v1alpha1
kind: HelmRelease
metadata:
  name: paperless-ngx-redis
  namespace: paperless
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 17.7.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: argocd
      interval: 5m
  values:
    architecture: standalone
    master:
      persistence:
        enabled: true
        existingClaim: paperless-ngx-redis
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    auth:
      enabled: false
