apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-secrets
  namespace: firefly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: firefly-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_PASSWORD
      remoteRef:
        key: /firefly/
        property: APP_PASSWORD
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /firefly/
        property: POSTGRES_PASSWORD
    - secretKey: PGPASSWORD
      remoteRef:
        key: /firefly/
        property: PGPASSWORD
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /firefly/
        property: POSTGRES_PASSWORD
