ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    extraArgs:
      default-ssl-certificate: |-
        networking/toolstowelsandfroods-com-tls
  tcp:
    22: gitea/gitea-ssh:22
