app-template:
  controller:
    replicas: 1
    type: statefulset
  image:
    repository: ghcr.io/onedr0p/sonarr-develop
    tag: 4.0.0.539
  env:
    TZ: Europe/Ljubljana
    SONARR__INSTANCE_NAME: Sonarr
    SONARR__PORT: &port 80
    SONARR__LOG_LEVEL: info
  service:
    main:
      ports:
        http:
          port: *port
  probes:
    liveness: &probes
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /ping
          port: *port
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
    readiness: *probes
    startup:
      enabled: false
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: television
        hajimari.io/appName: Sonarr
        hajimari.io/info: TV show collection manager for Usenet and BitTorrent users
      hosts:
       - host: &host shows.toolstowelsandfroods.com
         paths:
           - path: /
             pathType: Prefix
      tls:
        - secretName: sonarr-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteMany
      size: 1Gi
    media:
      enabled: true
      type: nfs
      server: 192.168.1.89
      path: /volume1/k3s/data
      mountPath: /media
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
    limits:
      memory: 1000Mi
